//

import '../core/models/address/address.dart';

List<Address> addressList = [
  Address(
    address1: "Cotonou",
    address2: "Calavi",
    city: "Cotonou",
    country: "Benin",
    countryCode: "bj",
    latitude: "22°N",
    longitude: "120°E",
    name: "Cotonou",
    province: "12300",
    provinceCode: "20312",
    zip: "0235",
  ),
  Address(
    address1: "Porto-Novo",
    address2: "Cotonou",
    city: "Porto-Novo",
    country: "Benin",
    countryCode: "bj",
    latitude: "22°N",
    longitude: "120°E",
    name: "Porto-Novo",
    province: "12300",
    provinceCode: "20312",
    zip: "0235",
  ),
  Address(
    address1: "Parakou",
    address2: "Cotonou",
    city: "Parakou",
    country: "Benin",
    countryCode: "bj",
    latitude: "22°N",
    longitude: "120°E",
    name: "Porto-Novo",
    province: "12300",
    provinceCode: "20312",
    zip: "0235",
  ),
  Address(
    address1: "Bohicon",
    address2: "Cotonou",
    city: "Bohicon",
    country: "Benin",
    countryCode: "bj",
    latitude: "22°N",
    longitude: "120°E",
    name: "Porto-Novo",
    province: "12300",
    provinceCode: "20312",
    zip: "0235",
  ),
  Address(
    address1: "Bohicon",
    address2: "Cotonou",
    city: "Calavi",
    country: "Benin",
    countryCode: "bj",
    latitude: "22°N",
    longitude: "120°E",
    name: "Porto-Novo",
    province: "12300",
    provinceCode: "20312",
    zip: "0235",
  ),
];
